/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package autonoma.ployectosimulador.views;

import autonoma.ployectosimulador.models.Carro;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author mateo
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    /////////////////////////////////
    /// Clases
    
    private Carro carro;
    public PantallaPrincipal(Carro carro) {
        initComponents();
        
        
        //para que ejecute en la mitad
        this.setLocationRelativeTo(null);
        this.carro = carro;
        this.TxtEstado.setText("APAGADO");
        this.TxtVelocidad.setText(Integer.toString(this.carro.getVelocidad()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Pantalla1 = new javax.swing.JPanel();
        Pantalla2 = new javax.swing.JPanel();
        imanCarro = new javax.swing.JLabel();
        BtnEncendido = new javax.swing.JButton();
        BtnApagar = new javax.swing.JButton();
        IconLlantas = new javax.swing.JLabel();
        IconMotor = new javax.swing.JLabel();
        TituVelocidad = new javax.swing.JLabel();
        TituEstado = new javax.swing.JLabel();
        TituVelocidaMaxima = new javax.swing.JLabel();
        TituLImite = new javax.swing.JLabel();
        TituNombreLLantas = new javax.swing.JLabel();
        TituTipoMotor = new javax.swing.JLabel();
        BtnFrenar = new javax.swing.JPanel();
        IconFrenar = new javax.swing.JLabel();
        TxtFrenar = new javax.swing.JLabel();
        BtnAcerelar = new javax.swing.JPanel();
        IconAcerelar = new javax.swing.JLabel();
        TxtAcelerar = new javax.swing.JLabel();
        TxtEstado = new javax.swing.JLabel();
        TxtVelocidad = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Pantalla1.setBackground(new java.awt.Color(204, 0, 0));
        Pantalla1.setForeground(new java.awt.Color(255, 51, 51));

        Pantalla2.setBackground(new java.awt.Color(255, 255, 255));

        imanCarro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autonoma/ployectosimulador/imagenes/OIP.jpg"))); // NOI18N

        BtnEncendido.setBackground(new java.awt.Color(0, 0, 0));
        BtnEncendido.setForeground(new java.awt.Color(255, 255, 255));
        BtnEncendido.setText("On");
        BtnEncendido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEncendidoActionPerformed(evt);
            }
        });

        BtnApagar.setBackground(new java.awt.Color(0, 0, 0));
        BtnApagar.setForeground(new java.awt.Color(255, 255, 255));
        BtnApagar.setText("Off");
        BtnApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnApagarActionPerformed(evt);
            }
        });

        IconLlantas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autonoma/ployectosimulador/imagenes/carreras.png"))); // NOI18N

        IconMotor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autonoma/ployectosimulador/imagenes/motor-del-coche.png"))); // NOI18N

        TituVelocidad.setBackground(new java.awt.Color(0, 0, 0));
        TituVelocidad.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        TituVelocidad.setForeground(new java.awt.Color(0, 0, 0));
        TituVelocidad.setText("Valocidad");

        TituEstado.setBackground(new java.awt.Color(0, 0, 0));
        TituEstado.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        TituEstado.setForeground(new java.awt.Color(0, 0, 0));
        TituEstado.setText("Estado :");

        TituVelocidaMaxima.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        TituVelocidaMaxima.setForeground(new java.awt.Color(51, 51, 51));
        TituVelocidaMaxima.setText("Velocidad Maxima");
        TituVelocidaMaxima.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        TituLImite.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        TituLImite.setForeground(new java.awt.Color(51, 51, 51));
        TituLImite.setText("Limite");
        TituLImite.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        TituNombreLLantas.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        TituNombreLLantas.setForeground(new java.awt.Color(51, 51, 51));
        TituNombreLLantas.setText("Nombre Llanta");
        TituNombreLLantas.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        TituTipoMotor.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        TituTipoMotor.setForeground(new java.awt.Color(51, 51, 51));
        TituTipoMotor.setText("Tipo Motor");
        TituTipoMotor.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        BtnFrenar.setBackground(new java.awt.Color(255, 255, 255));
        BtnFrenar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnFrenarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnFrenarMouseExited(evt);
            }
        });

        IconFrenar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autonoma/ployectosimulador/imagenes/embrague.png"))); // NOI18N
        IconFrenar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                IconFrenarMouseEntered(evt);
            }
        });

        TxtFrenar.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        TxtFrenar.setForeground(new java.awt.Color(51, 51, 51));
        TxtFrenar.setText("Frenar");
        TxtFrenar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout BtnFrenarLayout = new javax.swing.GroupLayout(BtnFrenar);
        BtnFrenar.setLayout(BtnFrenarLayout);
        BtnFrenarLayout.setHorizontalGroup(
            BtnFrenarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnFrenarLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(BtnFrenarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TxtFrenar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IconFrenar))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        BtnFrenarLayout.setVerticalGroup(
            BtnFrenarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnFrenarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IconFrenar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TxtFrenar)
                .addContainerGap())
        );

        BtnAcerelar.setBackground(new java.awt.Color(255, 255, 255));
        BtnAcerelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnAcerelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnAcerelarMouseExited(evt);
            }
        });

        IconAcerelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autonoma/ployectosimulador/imagenes/acelerador.png"))); // NOI18N

        TxtAcelerar.setBackground(new java.awt.Color(0, 0, 0));
        TxtAcelerar.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        TxtAcelerar.setForeground(new java.awt.Color(51, 51, 51));
        TxtAcelerar.setText("Acererlar");
        TxtAcelerar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout BtnAcerelarLayout = new javax.swing.GroupLayout(BtnAcerelar);
        BtnAcerelar.setLayout(BtnAcerelarLayout);
        BtnAcerelarLayout.setHorizontalGroup(
            BtnAcerelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnAcerelarLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(BtnAcerelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IconAcerelar)
                    .addComponent(TxtAcelerar))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        BtnAcerelarLayout.setVerticalGroup(
            BtnAcerelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnAcerelarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IconAcerelar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtAcelerar)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        TxtEstado.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        TxtEstado.setForeground(new java.awt.Color(0, 0, 0));

        TxtVelocidad.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        TxtVelocidad.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout Pantalla2Layout = new javax.swing.GroupLayout(Pantalla2);
        Pantalla2.setLayout(Pantalla2Layout);
        Pantalla2Layout.setHorizontalGroup(
            Pantalla2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pantalla2Layout.createSequentialGroup()
                .addGroup(Pantalla2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pantalla2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(Pantalla2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnEncendido)
                            .addComponent(BtnApagar))
                        .addGap(36, 36, 36)
                        .addComponent(BtnFrenar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnAcerelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(Pantalla2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Pantalla2Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(TituEstado)
                                .addGap(18, 18, 18)
                                .addComponent(TxtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Pantalla2Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(TituVelocidad)
                                .addGap(12, 12, 12)
                                .addComponent(TxtVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(Pantalla2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(imanCarro)
                        .addGap(18, 18, 18)
                        .addGroup(Pantalla2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Pantalla2Layout.createSequentialGroup()
                                .addComponent(IconLlantas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(Pantalla2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TituLImite)
                                    .addComponent(TituNombreLLantas)))
                            .addGroup(Pantalla2Layout.createSequentialGroup()
                                .addComponent(IconMotor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(Pantalla2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TituVelocidaMaxima)
                                    .addComponent(TituTipoMotor))))))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        Pantalla2Layout.setVerticalGroup(
            Pantalla2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pantalla2Layout.createSequentialGroup()
                .addGroup(Pantalla2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Pantalla2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(imanCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Pantalla2Layout.createSequentialGroup()
                        .addGroup(Pantalla2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pantalla2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(TituNombreLLantas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TituLImite)
                                .addGap(30, 30, 30))
                            .addGroup(Pantalla2Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(IconLlantas)
                                .addGap(18, 18, 18)))
                        .addGroup(Pantalla2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(IconMotor)
                            .addGroup(Pantalla2Layout.createSequentialGroup()
                                .addComponent(TituTipoMotor)
                                .addGap(18, 18, 18)
                                .addComponent(TituVelocidaMaxima)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Pantalla2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pantalla2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(Pantalla2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TituEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Pantalla2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TituVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Pantalla2Layout.createSequentialGroup()
                        .addGroup(Pantalla2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Pantalla2Layout.createSequentialGroup()
                                .addComponent(BtnEncendido, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BtnApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(BtnFrenar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnAcerelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 2, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout Pantalla1Layout = new javax.swing.GroupLayout(Pantalla1);
        Pantalla1.setLayout(Pantalla1Layout);
        Pantalla1Layout.setHorizontalGroup(
            Pantalla1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pantalla1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(Pantalla2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        Pantalla1Layout.setVerticalGroup(
            Pantalla1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pantalla1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(Pantalla2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(Pantalla1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pantalla1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnEncendidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEncendidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnEncendidoActionPerformed

    private void BtnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnApagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnApagarActionPerformed
    /////////////////////////////////////////////////////////////
    /// Frenar color
    private void IconFrenarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconFrenarMouseEntered
        this.moueseEntered(BtnFrenar);
    }//GEN-LAST:event_IconFrenarMouseEntered

    private void BtnFrenarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnFrenarMouseEntered
        this.moueseEntered(BtnFrenar);
    }//GEN-LAST:event_BtnFrenarMouseEntered

    private void BtnFrenarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnFrenarMouseExited
        
        this.moueseExited(BtnFrenar);
    }//GEN-LAST:event_BtnFrenarMouseExited

    private void BtnAcerelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAcerelarMouseEntered
        this.moueseEntered(BtnAcerelar);
    }//GEN-LAST:event_BtnAcerelarMouseEntered

    private void BtnAcerelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAcerelarMouseExited
        this.moueseExited(BtnAcerelar);
    }//GEN-LAST:event_BtnAcerelarMouseExited


    private void moueseEntered(JPanel panel){
        
       // cundo el mouese esta ensima del boton
      // color al panel cambia  
     panel.setBackground(new Color(102,102,102));
    
    }
    
    private void moueseExited(JPanel panel){
        
       // cundo el mouese esta fuera del boton
      // color al panel cambia  
     panel.setBackground(new Color(255,255,255));
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BtnAcerelar;
    private javax.swing.JButton BtnApagar;
    private javax.swing.JButton BtnEncendido;
    private javax.swing.JPanel BtnFrenar;
    private javax.swing.JLabel IconAcerelar;
    private javax.swing.JLabel IconFrenar;
    private javax.swing.JLabel IconLlantas;
    private javax.swing.JLabel IconMotor;
    private javax.swing.JPanel Pantalla1;
    private javax.swing.JPanel Pantalla2;
    private javax.swing.JLabel TituEstado;
    private javax.swing.JLabel TituLImite;
    private javax.swing.JLabel TituNombreLLantas;
    private javax.swing.JLabel TituTipoMotor;
    private javax.swing.JLabel TituVelocidaMaxima;
    private javax.swing.JLabel TituVelocidad;
    private javax.swing.JLabel TxtAcelerar;
    private javax.swing.JLabel TxtEstado;
    private javax.swing.JLabel TxtFrenar;
    private javax.swing.JLabel TxtVelocidad;
    private javax.swing.JLabel imanCarro;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
