/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package autonoma.Restuarante.views;

import autonoma.Restuarante.models.Cena;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author mateo
 */
public class Ventana extends javax.swing.JFrame {

    
    /////////////////////////////////
    /// Clases
    
    private Cena cena;
    
    ///se crea un booleano ateder para que se pueda saber si el cliente esta en una mesa 
    private boolean ateder;
    public Ventana(Cena cena) {
        initComponents();
        
        //para que ejecute en la mitad
        this.setLocationRelativeTo(null);
        this.cena = cena;
        this.ateder = false;
        

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FONDO = new javax.swing.JPanel();
        Titulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnMesa = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnMenu = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnDinero = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FONDO.setBackground(new java.awt.Color(245, 245, 220));
        FONDO.setMaximumSize(new java.awt.Dimension(950, 880));
        FONDO.setMinimumSize(new java.awt.Dimension(950, 880));
        FONDO.setPreferredSize(new java.awt.Dimension(950, 880));

        Titulo.setBackground(new java.awt.Color(0, 204, 153));

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("COLOMBIS");

        jLabel5.setFont(new java.awt.Font("STLiti", 0, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("restuarant");

        javax.swing.GroupLayout TituloLayout = new javax.swing.GroupLayout(Titulo);
        Titulo.setLayout(TituloLayout);
        TituloLayout.setHorizontalGroup(
            TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TituloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TituloLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(408, 408, 408))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TituloLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(447, 447, 447))))
        );
        TituloLayout.setVerticalGroup(
            TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TituloLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnMesa.setBackground(new java.awt.Color(161, 103, 201));
        btnMesa.setForeground(new java.awt.Color(161, 103, 201));
        btnMesa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMesaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMesaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMesaMouseExited(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autonoma/Restuarante/Imagenes/restaurante.png"))); // NOI18N

        javax.swing.GroupLayout btnMesaLayout = new javax.swing.GroupLayout(btnMesa);
        btnMesa.setLayout(btnMesaLayout);
        btnMesaLayout.setHorizontalGroup(
            btnMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMesaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        btnMesaLayout.setVerticalGroup(
            btnMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMesaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        btnMenu.setBackground(new java.awt.Color(161, 103, 201));
        btnMenu.setForeground(new java.awt.Color(161, 103, 201));
        btnMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMenuMouseExited(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autonoma/Restuarante/Imagenes/menu.png"))); // NOI18N

        javax.swing.GroupLayout btnMenuLayout = new javax.swing.GroupLayout(btnMenu);
        btnMenu.setLayout(btnMenuLayout);
        btnMenuLayout.setHorizontalGroup(
            btnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        btnMenuLayout.setVerticalGroup(
            btnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnMenuLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        btnDinero.setBackground(new java.awt.Color(161, 103, 201));
        btnDinero.setForeground(new java.awt.Color(161, 103, 201));
        btnDinero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDineroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDineroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDineroMouseExited(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autonoma/Restuarante/Imagenes/dinero.png"))); // NOI18N
        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout btnDineroLayout = new javax.swing.GroupLayout(btnDinero);
        btnDinero.setLayout(btnDineroLayout);
        btnDineroLayout.setHorizontalGroup(
            btnDineroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnDineroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        btnDineroLayout.setVerticalGroup(
            btnDineroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnDineroLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jLabel6.setFont(new java.awt.Font("Stencil", 0, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("mesa");

        jLabel8.setFont(new java.awt.Font("Stencil", 0, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("cuenta");

        javax.swing.GroupLayout FONDOLayout = new javax.swing.GroupLayout(FONDO);
        FONDO.setLayout(FONDOLayout);
        FONDOLayout.setHorizontalGroup(
            FONDOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Titulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(FONDOLayout.createSequentialGroup()
                .addGroup(FONDOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FONDOLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(btnMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FONDOLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(FONDOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FONDOLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(btnDinero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FONDOLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel8)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        FONDOLayout.setVerticalGroup(
            FONDOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FONDOLayout.createSequentialGroup()
                .addGroup(FONDOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, FONDOLayout.createSequentialGroup()
                        .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(FONDOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FONDOLayout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(btnMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(FONDOLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, FONDOLayout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(btnDinero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(FONDOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FONDOLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6))
                            .addGroup(FONDOLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel8)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FONDO, javax.swing.GroupLayout.PREFERRED_SIZE, 1076, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(FONDO, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //////////////////////////////////////////////////////////
    /// Mesa color
    private void btnMesaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMesaMouseEntered
        // cundo el mouese esta ensima de menu
        
        this.moueseEntered(btnMesa);
    }//GEN-LAST:event_btnMesaMouseEntered

    private void btnMesaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMesaMouseExited
        // cundo el mouese esta fuera del menu
        
        this.moueseExited(btnMesa);
    }//GEN-LAST:event_btnMesaMouseExited

    //////////////////////////////////////////////////////////
    /// Menu color
    private void btnMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMouseEntered
        // cundo el mouese esta ensima de menu
        
        this.moueseEntered(btnMenu);
    }//GEN-LAST:event_btnMenuMouseEntered

    private void btnMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMouseExited
        // cundo el mouese esta fuera del menu
        
        this.moueseExited(btnMenu);
    }//GEN-LAST:event_btnMenuMouseExited
    
   
    /////////////////////////////////////////////////////////////
    /// Dinero color
    private void btnDineroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDineroMouseEntered
        
        this.moueseEntered(btnDinero);
    }//GEN-LAST:event_btnDineroMouseEntered

    private void btnDineroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDineroMouseExited
        
        this.moueseExited(btnDinero);
    }//GEN-LAST:event_btnDineroMouseExited

    /////////////////////////////////////////////////////////////
    /// Mesa menu y dinero click
    
    private void btnMesaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMesaMouseClicked
        
        ///Error
        //tocara poner una valiabre vandela saque si se ingresa la valiabre ateder no se modifica 
        boolean vadela =false;
        OrganizarMesa ventanaOrganizar = new OrganizarMesa(this,true,cena,vadela);
        ventanaOrganizar.setVisible(true);
           System.out.println("Ventana principal"+vadela);
         if(vadela){
     
        System.out.println(vadela);
        this.ateder=true;
        System.out.println(this.ateder);
        }
        //el errro que tiene es tan grande que hay que hacer una codicion


    }//GEN-LAST:event_btnMesaMouseClicked

    private void btnMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMouseClicked

         if (ateder){
            
          JOptionPane.showMessageDialog(this, "porfavor organizate en una mesa");
            
      } else {
        Menu ventanaMenu = new Menu(this,true,cena); 
        ventanaMenu.setVisible(true);
        }
    }//GEN-LAST:event_btnMenuMouseClicked

    private void btnDineroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDineroMouseClicked
                CuentaJF ventanaCuenta = new CuentaJF(this,true,cena); 
        ventanaCuenta.setVisible(true);
            if (ateder){
            
          JOptionPane.showMessageDialog(this, "porfavor organizate en una mesa");
            
      } else {

                 }        
    }//GEN-LAST:event_btnDineroMouseClicked

    private void moueseEntered(JPanel panel){
        
        // cundo el mouese esta ensima de menu
        // da color al panel
        panel.setBackground(new Color(54,0,110));
    
    }
    private void moueseExited(JPanel panel){
        
        // cundo el mouese esta fuera del menu
        // da color al panel
        panel.setBackground(new Color(161,103,201));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FONDO;
    private javax.swing.JPanel Titulo;
    private javax.swing.JPanel btnDinero;
    private javax.swing.JPanel btnMenu;
    private javax.swing.JPanel btnMesa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
